import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< HEAD
import { CartProvider } from "./context/CartContext"; // <- Import CartProvider

// Fonts
=======

>>>>>>> origin/main
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<<<<<<< HEAD
// Metadata
export const metadata: Metadata = {
  title: "Flower Shop App",
  description: "Flower Blossom Shop built with Next.js",
};

// RootLayout
=======
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

>>>>>>> origin/main
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
<<<<<<< HEAD
        {/* Wrap everything in CartProvider for global cart state */}
        <CartProvider>{children}</CartProvider>
=======
        {children}
>>>>>>> origin/main
      </body>
    </html>
  );
}
